version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      SLACKTOKEN: ${SLACKTOKEN}
      CHANNELNAME: ${CHANNELNAME}
  redis:
    image: redis:alpine
    container_name: redis
  
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l DEBUG
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - redis
      - app    

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    volumes: 
      - flower_data:/data

volumes:
  flower_data: